### ISSUE TITLE
Problem with Multiple Syslog Loggers

### ISSUE THREAD

**Issue by tilo** [seattlerb/sysloglogger#6]
I'm using multiple Syslog::Logger instances, and am experiencing a problem with it. 

The Syslog::Logger instance that gets created first, gets log messages from all the other Syslog::Logger facilities as well, prefixed by their facility name -  it also correctly logs it's own data without prefix.

**Comment by zenspider** [comment]
This project was merged into ruby itself as of 2.0. Closing this ticket and shutting down the project.
